name: Build-Cron

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Check Version
        run: |
          bash ./build.sh

      - name: Commit & Push
        uses: timzu/act-build@master
        with:
          args: --commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE_PATH: ./target/commit_message

      # - name: Publish
      #   uses: timzu/act-build@master
      #   with:
      #     args: --publish
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     AWS_REGION: "eu-central-1"
      #     FROM_PATH: "./target/publish"
      #     DEST_PATH: "s3://repo.timzu.com/latest"
      #     OPTIONS: "--acl public-read"

      - name: Release
        uses: timzu/act-build@master
        with:
          args: --release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Push
        uses: timzu/act-build@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Post to Slack
      #   uses: timzu/act-build@master
      #   with:
      #     args: --slack
      #   env:
      #     SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
      #     JSON_PATH: ./target/slack_message.json
      #     LOOSE_ERROR: "true"
